[project]
name = "test-sql"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.4.0",
    "flask>=3.1.2",
    "pandas>=2.3.2",
    "pandasql>=0.7.3",
]
